### PR TITLE
Implement toString() in classes Constraint, Expressions, Variable.

### PR DESCRIPTION
**Pull request by brestac**
Also add Expression isConstant()

### CODE REVIEW

**Comment by IjzerenHein** [comment]
why did you close this?

**Comment by brestac** [comment]
Because I thought it made more sense to open it on the main repo. Finally i didn't and I opened a new improved PR here.

**Comment by IjzerenHein** [comment]
Thanks for the new pull request @cacaodev. I will try to pull and test it anytime soon.

A while back I asked the original author of the kiwi-ts code whether I could publish the code on npm but never got a response from him. I then asked again a while later but again no response. I still want to pull this on npm as I think this is the fastest cassowary solver available. I think I'm just gonna clean up the repo and make it javascript only (perhaps rename to kiwi-js). And then publish it to npm.

Just curious, where are you using it for?

cheers

**Comment by brestac** [comment]
I'm using it for porting Autolayout to the cappuccino web framework.
https://github.com/cacaodev/cappuccino/tree/Autolayout-kiwi
There are links to online examples in the Readme.

**Pull request closed without merging**
